### ISSUE TITLE
Problem in Joomla! 3.8.6

### ISSUE THREAD

**Issue by sancheznahu** [betweenbrain/Menu-Wrench#31]
Hi,

I'm experiencing a problem after update joomla! to version 3.8.6, the module no load submenu items.
The option "Show Sub-menu Items" its ok, any suggestion?

Best,

Nahuel.

**Comment by betweenbrain** [comment]
Hello,

Unfortunately, I haven’t been maintaining this module nor working with Joomla for a few years now. It is strange that an issue would appear with a maintenance release of Joomla. What version did you upgrade from? Can you please post any errors or relevant logs?

**Comment by sancheznahu** [comment]
Hello,

The versión of Joomla! installed before 3.8.6 was 3.3.6

The log of apache in error.log:

PHP Notice:  Indirect modification of overloaded property Joomla\\CMS\\Menu\\MenuItem::$children has no effect in /modules/mod_menuwrench/helper.php on line 84

Is there another relevant log?

Excuse me. My English is bad. I just speak Spanish.

Thanks!

Nahuel.

**Comment by betweenbrain** [comment]
Hello Nahuel,

If I had to guess, the issue probably occurred because of all of the changes the Joomla project made around 3.7.5 and 3.8. You'll find that many people had numerous issues with these versions. This module probably needs to be changed.

That being, I am not sure what to suggest as I am not currently using Joomla or supporting any Joomla sites.
